### PR TITLE
Protocols array

### LINKED ISSUE #2: API Gateway configure compatibility for both HTTP and HTTPS
## Problems:

In the [fullstack template](https://github.com/serverless/components/tree/master/templates/tencent-fullstack-vue-application), we could use express and website components to make a serverless app. API Gateway could support HTTP or HTTPS, and if users want their API to support both HTTP and HTTPS, they have to configure like this in `serverless.yml`:
```
api:
  component: '@serverless/tencent-express'
 inputs:
    region: ap-beijing
    code: ./api
    functionName: fullstack-api
    role: execute-scf
    functionConf:
      timeout: 30
      memorySize: 512
    apigatewayConf:
      protocol: http&https   # configure of protocol support 
```
then, when they deploy like this, after `sls --debug` deployment, we'll find the API could be visit by HTTP and HTTPS, while in the static page, it can't be recognized :
```
  frontend: 
    url: https://hsrrivj-kugobji-xxxx.cos-website.ap-beijing.myqcloud.com
    env: 
      apiUrl: http&https://service-nifeq8x7-xxxxx.bj.apigw.tencentcs.com/release/
  api: 
    region:              ap-beijing
    functionName:        fullstack-api-pg
    apiGatewayServiceId: service-nifeq8x7
    url:                 http&https://service-nifeq8x7-xxxx.bj.apigw.tencentcs.com/release/
```
the request url became like this: (api url will be reffered in env)
```
Request URL: https://hsrrivj-kugobji-xxx.cos-website.ap-beijing.myqcloud.com/http&https://service-nifeq8x7-xxxxx.bj.apigw.tencentcs.com/release/user
```
and it will return a 404 error.

### PR DESCRIPTION
**Pull request by pmuens**
This PR changes the config API to accept `protocols` defined as an array (rather than as a string).

It also introduces [tape](https://github.com/substack/tape) tests.

**Other code we might need to update**:
- [x] [tencent-express](https://github.com/serverless-components/tencent-express) --> [PR](https://github.com/serverless-components/tencent-express/pull/3)
- [x] [tencent-koa](https://github.com/serverless-components/tencent-koa) --> [PR](https://github.com/serverless-components/tencent-koa/pull/5)
- [x] [tencent-scf](https://github.com/serverless-components/tencent-scf) --> [PR](https://github.com/serverless-components/tencent-scf/pull/2)
- [x] [tencent-fullstack-react-application](https://github.com/serverless/components/tree/master/templates/tencent-fullstack-react-application) --> [PR](https://github.com/serverless/components/pull/539)
- [x] [tencent-fullstack-vue-application](https://github.com/serverless/components/tree/master/templates/tencent-fullstack-vue-application) --> [PR](https://github.com/serverless/components/pull/539)

Closes #2

### CODE REVIEW

**Comment by yugasun** [comment]
@pmuens If you change `protocol` to `protocols`，as you mentioned, we should update __`all`__ components depend on it. So why not just deal with `http&https` string in `tencent-apigateway` component?

**Comment by pmuens** [comment]
> @pmuens If you change protocol to protocols，as you mentioned, we should update all components depend on it. So why not just deal with http&https string in tencent-apigateway component?

thanks for the review. Yes, I agree that it's very unfortunate that we have to update all the dependent components (I'll of course take care of this in that case).

The main rationale here is that `http&https` is an implementation detail in the Tencent API and not a valid protocol. Turning this into an `array` provides a higher level of abstraction, therefore makes it more user friendly and hides the APIs implementation detail.

**Comment by pmuens** [comment]
@yugasun I've updated all the places where we've used `tencent-apigateway`.

**Comment by yugasun** [comment]
@pmuens Well done~

**Comment by pmuens** [comment]
> @pmuens Well done~

Thanks! :+1:

**Pull request merged**
